spring.datasource.initialization-mode : always
spring.datasource.platform : postgres
spring.datasource.driver-class-name : org.postgresql.Driver
spring.datasource.url : jdbc:postgresql://localhost:5432/testdb
spring.datasource.username : postgres
spring.datasource.password : 1111
spring.activemq.broker-url : tcp://localhost:61616
spring.activemq.user : admin
spring.activemq.password : admin
